# 1.	Write a Python Program to Add Two Matrices?

In [16]:
a= [[2,3,4], [3,4,5]]

In [17]:
b= [[3,3,4], [3,3,5]]
result= [[0,0,0], [0,0,0]]

In [18]:
for i in range(len(a)):
    for j in range(len(a[0])):
        result[i][j] = a[i][j] + b[i][j]
        
for r in result:
    print(r)



[5, 6, 8]
[6, 7, 10]


# 2.	Write a Python Program to Multiply Two Matrices?

In [19]:
for i in range(len(a)):
    for j in range(len(a[0])):
        result[i][j] = a[i][j] * b[i][j]
        
for r in result:
    print(r)



[6, 9, 16]
[9, 12, 25]


# 3.	Write a Python Program to Transpose a Matrix?

In [20]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


# 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [8]:
user_entry = input('string')

word = user_entry.split()
word.sort()

for i in word:
    print(i)

stringapple boy egg ant
ant
apple
boy
egg


# 5.	Write a Python Program to Remove Punctuation From a String?

In [5]:
punctuations = '''{}/!@#$%^&*()_--'''

In [6]:
string = "hello !@ --my $%name is __ekta"

In [7]:
no_pinc = ""
for i in string:
    if i not in punctuations:
        no_pinc = no_pinc + i
print(no_pinc)

hello  my name is ekta
